baseURL = "https://keyll0ger.github.io/"
languageCode = "en-us"
title = "keyll0ger"
theme = "PaperMod"
paginate = 10

[params]
  author = "keyll0ger"
  description = "CTF Writeups & Red Team Notes"
  env = "production"
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false

  [params.homeInfoParams]
    Title = "keyll0ger"
    Content = "Red Team | CTF Player | CRTA Certified\n\nCTF Writeups & Red Team Notes"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/keyll0ger"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  identifier = "writeups"
  name = "Writeups"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 20

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 30

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 40
